# Generated by Django 6.1.1 on 2026-10-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('project_type', models.CharField(choices=[('web', 'طراحی وب\u200cسایت'), ('shop', 'فروشگاه اینترنتی'), ('landing', 'لندینگ پیج'), ('dashboard', 'داشبورد/پنل'), ('admin', 'خدمات کامپیوتری و اداری'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع پروژه')),
                ('message', models.TextField(blank=True, max_length=1000, verbose_name='توضیح کوتاه پروژه')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شد'), ('done', 'انجام شد')], default='new', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'درخواست تماس',
                'verbose_name_plural': 'درخواست\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
    ]
