# Generated by Django 6.1.1 on 2026-10-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی'),
        ),
    ]
